CREATE TABLE timetable_lessons
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id     BIGINT,
    status        SMALLINT,
    created       TIMESTAMP WITHOUT TIME ZONE,
    updated       TIMESTAMP WITHOUT TIME ZONE,
    group_id      BIGINT,
    teacher_id    BIGINT,
    discipline_id BIGINT,
    room_id       BIGINT,
    lesson_number SMALLINT,
    day           SMALLINT,
    lesson_type   SMALLINT,
    week_type     SMALLINT,
    sub_group     SMALLINT,
    start_date    date,
    end_date      date,
    visible       BOOLEAN NOT NULL,
    CONSTRAINT pk_timetable_lessons PRIMARY KEY (id)
);
ALTER TABLE timetable_lessons
    ADD CONSTRAINT FK_TIMETABLE_LESSONS_ON_DISCIPLINE FOREIGN KEY (discipline_id) REFERENCES dean_disciplines (id);
ALTER TABLE timetable_lessons
    ADD CONSTRAINT FK_TIMETABLE_LESSONS_ON_GROUP FOREIGN KEY (group_id) REFERENCES dean_groups (id);
ALTER TABLE timetable_lessons
    ADD CONSTRAINT FK_TIMETABLE_LESSONS_ON_ROOM FOREIGN KEY (room_id) REFERENCES dean_rooms (id);
ALTER TABLE timetable_lessons
    ADD CONSTRAINT FK_TIMETABLE_LESSONS_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES dean_teachers (id);