CREATE TABLE dean_statement_teacher_merge
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id  BIGINT,
    status     SMALLINT,
    created    TIMESTAMP WITHOUT TIME ZONE,
    updated    TIMESTAMP WITHOUT TIME ZONE,
    ssm_id     BIGINT,
    teacher_id BIGINT,
    CONSTRAINT pk_dean_statement_teacher_merge PRIMARY KEY (id)
);

ALTER TABLE dean_statement_teacher_merge
    ADD CONSTRAINT FK_DEAN_STATEMENT_TEACHER_MERGE_ON_SSM FOREIGN KEY (ssm_id) REFERENCES dean_statement_student_merge (id);

ALTER TABLE dean_statement_teacher_merge
    ADD CONSTRAINT FK_DEAN_STATEMENT_TEACHER_MERGE_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES dean_teachers (id);