CREATE TABLE internal_messages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id       BIGINT,
    status          INTEGER,
    created         TIMESTAMP WITHOUT TIME ZONE,
    updated         TIMESTAMP WITHOUT TIME ZONE,
    title           VARCHAR(255),
    message         VARCHAR(4096),
    inactive        BOOLEAN                                 NOT NULL,
    cron_expression VARCHAR(255),
    message_type    INTEGER,
    CONSTRAINT pk_internal_messages PRIMARY KEY (id)
);