ALTER TABLE documents
    DROP CONSTRAINT fk_documents_on_citizenship;

ALTER TABLE documents
    DROP CONSTRAINT fk_documents_on_institution;

ALTER TABLE documents
    DROP CONSTRAINT fk_documents_on_student_language;

ALTER TABLE students
    DROP CONSTRAINT fk_students_on_last_deviation;

ALTER TABLE students
    DROP CONSTRAINT fk_students_on_last_document;

CREATE TABLE addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id  BIGINT,
    status     SMALLINT,
    created    TIMESTAMP WITHOUT TIME ZONE,
    updated    TIMESTAMP WITHOUT TIME ZONE,
    address    VARCHAR(255),
    country    VARCHAR(255),
    post_index VARCHAR(255),
    state      VARCHAR(255),
    region     VARCHAR(255),
    city       VARCHAR(255),
    street     VARCHAR(255),
    house      VARCHAR(255),
    house_part VARCHAR(255),
    flat       VARCHAR(255),
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE citizenship
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id BIGINT,
    status    SMALLINT,
    created   TIMESTAMP WITHOUT TIME ZONE,
    updated   TIMESTAMP WITHOUT TIME ZONE,
    name      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_citizenship PRIMARY KEY (id)
);

CREATE TABLE parents
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id  BIGINT,
    status     SMALLINT,
    created    TIMESTAMP WITHOUT TIME ZONE,
    updated    TIMESTAMP WITHOUT TIME ZONE,
    student_id BIGINT,
    surname    VARCHAR(255),
    name       VARCHAR(255),
    patronymic VARCHAR(255),
    job        VARCHAR(255),
    phone_id   BIGINT,
    CONSTRAINT pk_parents PRIMARY KEY (id)
);

CREATE TABLE passports
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id             BIGINT,
    status                SMALLINT,
    created               TIMESTAMP WITHOUT TIME ZONE,
    updated               TIMESTAMP WITHOUT TIME ZONE,
    passport_type         SMALLINT                                NOT NULL,
    passport_serial       VARCHAR(255)                            NOT NULL,
    passport_number       VARCHAR(255)                            NOT NULL,
    passport_issue_date   date                                    NOT NULL,
    passport_issue_string VARCHAR(255)                            NOT NULL,
    passport_id           VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_passports PRIMARY KEY (id)
);

CREATE TABLE penalties
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id        BIGINT,
    status           SMALLINT,
    created          TIMESTAMP WITHOUT TIME ZONE,
    updated          TIMESTAMP WITHOUT TIME ZONE,
    student_id       BIGINT,
    date_liquidation TIMESTAMP WITHOUT TIME ZONE,
    reason_id        BIGINT,
    order_number     VARCHAR(255),
    order_text       VARCHAR(255),
    CONSTRAINT pk_penalties PRIMARY KEY (id)
);

CREATE TABLE phones
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id BIGINT,
    status    SMALLINT,
    created   TIMESTAMP WITHOUT TIME ZONE,
    updated   TIMESTAMP WITHOUT TIME ZONE,
    type      SMALLINT,
    phone     VARCHAR(255),
    CONSTRAINT pk_phones PRIMARY KEY (id)
);

CREATE TABLE reasons
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id BIGINT,
    status    SMALLINT,
    created   TIMESTAMP WITHOUT TIME ZONE,
    updated   TIMESTAMP WITHOUT TIME ZONE,
    name      VARCHAR(255),
    CONSTRAINT pk_reasons PRIMARY KEY (id)
);

CREATE TABLE student_changes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id           BIGINT,
    status              SMALLINT,
    created             TIMESTAMP WITHOUT TIME ZONE,
    updated             TIMESTAMP WITHOUT TIME ZONE,
    student_id          BIGINT,
    student_change_type SMALLINT,
    reason_id           BIGINT,
    order_number        VARCHAR(255),
    order_text          VARCHAR(255),
    msg                 VARCHAR(2048),
    msg_date            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_student_changes PRIMARY KEY (id)
);

ALTER TABLE students
    ADD address_id BIGINT;

ALTER TABLE students
    ADD birth_date date;

ALTER TABLE students
    ADD birth_place VARCHAR(255);

ALTER TABLE students
    ADD case_no BIGINT;

ALTER TABLE students
    ADD citizenship_id BIGINT;

ALTER TABLE students
    ADD document_number BIGINT;

ALTER TABLE students
    ADD education_string VARCHAR(255);

ALTER TABLE students
    ADD education_year_end INTEGER;

ALTER TABLE students
    ADD email VARCHAR(255);

ALTER TABLE students
    ADD enroll_date date;

ALTER TABLE students
    ADD enrollment_date date;

ALTER TABLE students
    ADD first_namel VARCHAR(255);

ALTER TABLE students
    ADD full_namel VARCHAR(255);

ALTER TABLE students
    ADD institution BIGINT;

ALTER TABLE students
    ADD job VARCHAR(255);

ALTER TABLE students
    ADD job_experience DOUBLE PRECISION;

ALTER TABLE students
    ADD maiden_name VARCHAR(255);

ALTER TABLE students
    ADD move BOOLEAN;

ALTER TABLE students
    ADD need_hostel BOOLEAN;

ALTER TABLE students
    ADD passport_id BIGINT;

ALTER TABLE students
    ADD payment_type SMALLINT;

ALTER TABLE students
    ADD phone_id BIGINT;

ALTER TABLE students
    ADD re_enroll BOOLEAN;

ALTER TABLE students
    ADD reg_address_id BIGINT;

ALTER TABLE students
    ADD state_support BOOLEAN;

ALTER TABLE students
    ADD student_language_id BIGINT;

ALTER TABLE students
    ADD unbound VARCHAR(255);

ALTER TABLE students
    ALTER COLUMN birth_date SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN birth_place SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN citizenship_id SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN education_string SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN first_namel SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN full_namel SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN move SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN need_hostel SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN re_enroll SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN state_support SET NOT NULL;

ALTER TABLE students
    ALTER COLUMN student_language_id SET NOT NULL;

ALTER TABLE parents
    ADD CONSTRAINT uc_parents_phone UNIQUE (phone_id);

ALTER TABLE students
    ADD CONSTRAINT uc_students_phone UNIQUE (phone_id);

ALTER TABLE parents
    ADD CONSTRAINT FK_PARENTS_ON_PHONE FOREIGN KEY (phone_id) REFERENCES phones (id);

ALTER TABLE parents
    ADD CONSTRAINT FK_PARENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE penalties
    ADD CONSTRAINT FK_PENALTIES_ON_REASON FOREIGN KEY (reason_id) REFERENCES reasons (id);

ALTER TABLE penalties
    ADD CONSTRAINT FK_PENALTIES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_CITIZENSHIP FOREIGN KEY (citizenship_id) REFERENCES citizenship (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_INSTITUTION FOREIGN KEY (institution) REFERENCES institutions (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_PASSPORT FOREIGN KEY (passport_id) REFERENCES passports (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_PHONE FOREIGN KEY (phone_id) REFERENCES phones (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_REG_ADDRESS FOREIGN KEY (reg_address_id) REFERENCES addresses (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_STUDENT_LANGUAGE FOREIGN KEY (student_language_id) REFERENCES student_language (id);

ALTER TABLE student_changes
    ADD CONSTRAINT FK_STUDENT_CHANGES_ON_REASON FOREIGN KEY (reason_id) REFERENCES reasons (id);

ALTER TABLE student_changes
    ADD CONSTRAINT FK_STUDENT_CHANGES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

DROP TABLE citizenhips CASCADE;

DROP TABLE documents CASCADE;

ALTER TABLE students
    DROP COLUMN address;

ALTER TABLE students
    DROP COLUMN address_city;

ALTER TABLE students
    DROP COLUMN address_country;

ALTER TABLE students
    DROP COLUMN address_flat;

ALTER TABLE students
    DROP COLUMN address_house;

ALTER TABLE students
    DROP COLUMN address_house_part;

ALTER TABLE students
    DROP COLUMN address_index;

ALTER TABLE students
    DROP COLUMN address_region;

ALTER TABLE students
    DROP COLUMN address_state;

ALTER TABLE students
    DROP COLUMN address_street;

ALTER TABLE students
    DROP COLUMN city_is_village;

ALTER TABLE students
    DROP COLUMN city_type;

ALTER TABLE students
    DROP COLUMN last_deviation_id;

ALTER TABLE students
    DROP COLUMN last_document_id;

ALTER TABLE students
    DROP COLUMN phone;

ALTER TABLE teacher_department_merge
    ALTER COLUMN department_id SET NOT NULL;

ALTER TABLE educations
    ALTER COLUMN education SET NOT NULL;

ALTER TABLE educations
    ALTER COLUMN education_document_number SET NOT NULL;

ALTER TABLE educations
    ALTER COLUMN education_document_serial SET NOT NULL;

ALTER TABLE educations
    ALTER COLUMN education_document_type SET NOT NULL;

ALTER TABLE groups
    DROP COLUMN end_semester;

ALTER TABLE groups
    ADD end_semester SMALLINT;

ALTER TABLE groups
    ALTER COLUMN faculty_id SET NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN frame SET NOT NULL;

ALTER TABLE institutions
    ALTER COLUMN full_name SET NOT NULL;

ALTER TABLE hostel_rooms
    ALTER COLUMN hostel SET NOT NULL;

ALTER TABLE teacher_degrees
    DROP COLUMN hour_price;

ALTER TABLE teacher_degrees
    ADD hour_price DOUBLE PRECISION;

ALTER TABLE internal_messages
    ALTER COLUMN message SET NOT NULL;

ALTER TABLE internal_messages
    DROP COLUMN message_type;

ALTER TABLE internal_messages
    DROP COLUMN status;

ALTER TABLE internal_messages
    ADD message_type SMALLINT NOT NULL;

ALTER TABLE internal_messages
    ALTER COLUMN message_type SET NOT NULL;

ALTER TABLE faculties
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE groups
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE specializations
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE student_language
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE teacher_degrees
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE specializations
    ALTER COLUMN qualification_id SET NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN room_number TYPE VARCHAR(255) USING (room_number::VARCHAR(255));

ALTER TABLE rooms
    ALTER COLUMN room_number SET NOT NULL;

ALTER TABLE hostel_rooms
    ALTER COLUMN room_type SET NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN room_type SET NOT NULL;

ALTER TABLE faculties
    ALTER COLUMN short_name SET NOT NULL;

ALTER TABLE specialities
    ALTER COLUMN short_name SET NOT NULL;

ALTER TABLE specializations
    ALTER COLUMN short_name SET NOT NULL;

ALTER TABLE specialities
    ALTER COLUMN spec_code SET NOT NULL;

ALTER TABLE specializations
    ALTER COLUMN spez_code SET NOT NULL;

ALTER TABLE internal_messages
    ADD status SMALLINT;

ALTER TABLE educations
    ALTER COLUMN student_id SET NOT NULL;

ALTER TABLE teacher_department_merge
    ALTER COLUMN teacher_id SET NOT NULL;

ALTER TABLE internal_messages
    ALTER COLUMN title SET NOT NULL;